# Generated by Django 4.2 on 2025-08-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product_Category', '0001_initial'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('nameProduct', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion del producto')),
                ('price_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Costo del producto')),
                ('price_selling', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Venta del producto')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Stock Minimo')),
                ('categoryfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_categoria', to='Product_Category.product_category', verbose_name='Categoría del Producto')),
                ('supplierfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_proveedor', to='Supplier.supplier', verbose_name='Proveedor del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
