# Generated by Django 4.2 on 2025-08-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('idCustomer', models.AutoField(primary_key=True, serialize=False)),
                ('CustName', models.CharField(max_length=120, verbose_name='Nombre del Cliente')),
                ('CustLastName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido del Cliente')),
                ('Cust_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono del cliente')),
                ('Cust_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='Email del cliente')),
                ('CustAddress', models.CharField(blank=True, max_length=120, null=True, verbose_name='Direccion del cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
