# Generated by Django 4.2 on 2025-08-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metPayment',
            fields=[
                ('idPayment', models.AutoField(primary_key=True, serialize=False)),
                ('namePayment', models.CharField(max_length=100, unique=True, verbose_name='Nombre de forma de pago')),
                ('DescriptionPayment', models.TextField(blank=True, null=True, verbose_name='Descripción de la forma de pago')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
            },
        ),
    ]
