# Generated by Django 4.2 on 2025-08-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '__first__'),
        ('Sales_product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailSalesProduct',
            fields=[
                ('idDetailSalesProduct', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_detailSales', models.PositiveIntegerField(verbose_name='Cantidad Vendida')),
                ('price_Unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario en la venta')),
                ('productFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product', verbose_name='Producto')),
                ('saleFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_Ventas', to='Sales_product.sales_product', verbose_name='Detalle de Ventas')),
            ],
            options={
                'verbose_name': 'Detalle de ventas',
                'verbose_name_plural': 'Detalles de ventas',
            },
        ),
    ]
