# Generated by Django 4.2 on 2025-08-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('idSupplier', models.AutoField(primary_key=True, serialize=False)),
                ('nameSupplier', models.CharField(max_length=150, verbose_name='Nombre del proveedor')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de la persona')),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de telefono')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email de la persona')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
