# Generated by Django 4.2 on 2025-08-19 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_product',
            fields=[
                ('idPurchase', models.AutoField(primary_key=True, serialize=False)),
                ('dateSale', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('total_purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la compra')),
                ('supplierfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Supplier.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra de producto',
                'verbose_name_plural': 'Compras de productos',
            },
        ),
    ]
