# Generated by Django 4.2 on 2025-08-20 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_product',
            name='dateSale',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra'),
        ),
    ]
