# Generated by Django 4.2 on 2025-08-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase_product', '0002_alter_purchase_product_datesale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_product',
            old_name='dateSale',
            new_name='datePurchase',
        ),
    ]
