# Generated by Django 4.2 on 2025-08-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Purchase_product', '__first__'),
        ('Product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_purchase',
            fields=[
                ('idDetailPurchase', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad comprada')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario en la compra')),
                ('productfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product', verbose_name='Producto')),
                ('purchaseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='Purchase_product.purchase_product', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de compras',
            },
        ),
    ]
