# Generated by Django 4.2 on 2025-08-19 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Met_Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_product',
            fields=[
                ('idSalesProduct', models.AutoField(primary_key=True, serialize=False)),
                ('dateSales', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de venta')),
                ('customerFk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer', verbose_name='Cliente')),
                ('met_paymentFk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Met_Payment.metpayment', verbose_name='Forma de pago')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de ventas',
            },
        ),
    ]
