# Generated by Django 4.2 on 2025-08-20 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_product',
            name='dateSales',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta'),
        ),
    ]
